from __future__ import annotations

from typing import Any, Awaitable, Callable, Iterable, Protocol, runtime_checkable

from .entities import (
    CategoryKind,
    ChannelKind,
    IceServer,
    OfferPreparation,
    Packet,
    Peer,
)


@runtime_checkable
class IClock(Protocol):
    def now(self) -> float: ...
    def monotonic(self) -> float: ...


@runtime_checkable
class ILogger(Protocol):
    def debug(self, msg: str, *args: Any) -> None: ...
    def info(self, msg: str, *args: Any) -> None: ...
    def warning(self, msg: str, *args: Any) -> None: ...
    def error(self, msg: str, *args: Any) -> None: ...


@runtime_checkable
class ICodec(Protocol):
    def encode(self, packet: Packet) -> bytes: ...
    def decode(self, data: bytes) -> Packet: ...


@runtime_checkable
class IScheduler(Protocol):
    def schedule(self, callback: Callable[[], None], interval_seconds: float) -> None: ...
    def cancel(self, callback: Callable[[], None]) -> None: ...


@runtime_checkable
class IAsyncRunner(Protocol):
    def run_coroutine(self, coro: Awaitable[Any]) -> None: ...
    def run_coroutine_blocking(
        self, coro: Awaitable[Any], timeout: float | None = ...
    ) -> Any: ...
    def call_soon(self, fn: Callable[..., Any], *args: Any) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...


@runtime_checkable
class ISceneDirtyCollector(Protocol):
    """Sender-side scene access: query dirty ops without applying remote."""
    def is_applying_remote(self) -> bool: ...
    def collect_dirty_ops(
        self, categories: Iterable[CategoryKind]
    ) -> list[tuple[CategoryKind, list[dict[str, Any]]]]: ...


@runtime_checkable
class ISceneApplier(Protocol):
    """Receiver-side scene access: apply remote ops with echo guard."""
    def set_applying_remote(self, value: bool) -> None: ...
    def apply_ops(
        self, category: CategoryKind, ops: list[dict[str, Any]]
    ) -> None: ...


@runtime_checkable
class ISceneSnapshot(Protocol):
    """Full-state read for Force Push and Initial Snapshot."""
    def build_full_snapshot(
        self, *, initial_snapshot: bool = False,
    ) -> list[tuple[CategoryKind, list[dict[str, Any]]]]: ...
    def set_applying_remote(self, value: bool) -> None: ...
    def apply_ops(
        self, category: CategoryKind, ops: list[dict[str, Any]]
    ) -> None: ...


@runtime_checkable
class ISceneLifecycle(Protocol):
    """Install/uninstall depsgraph + msgbus listeners. Owned by Composition Root."""
    def install_change_listeners(self) -> None: ...
    def uninstall_change_listeners(self) -> None: ...


@runtime_checkable
class ISceneGateway(
    ISceneDirtyCollector,
    ISceneApplier,
    ISceneSnapshot,
    ISceneLifecycle,
    Protocol,
):
    """Aggregate scene gateway used by the Composition Root.

    UseCases should depend on the narrowest sub-protocol they need rather
    than this aggregate, to keep test fakes small.
    """
    ...


RecvCallback = Callable[[ChannelKind, bytes], None]
StateChangeCallback = Callable[[str], None]


@runtime_checkable
class ITransport(Protocol):
    def configure(self, ice_servers: tuple[IceServer, ...]) -> None: ...

    async def create_offer(self) -> str: ...
    async def create_answer(self, offer_sdp: str) -> str: ...
    async def accept_answer(self, answer_sdp: str) -> None: ...

    async def gather_complete(self, timeout: float) -> None: ...
    def local_description(self) -> str | None: ...

    async def send(self, channel: ChannelKind, data: bytes) -> None: ...
    def on_recv(self, callback: RecvCallback) -> None: ...
    def on_state_change(self, callback: StateChangeCallback) -> None: ...

    async def close(self) -> None: ...


@runtime_checkable
class ISignalingProvider(Protocol):
    name: str

    async def prepare_offer(
        self, room_id: str, sdp: str, token_codec: "ITokenCodec"
    ) -> OfferPreparation:
        """Publish or encode the offer, return token + post-status."""

    async def publish_offer(self, room_id: str, sdp: str) -> None: ...
    async def wait_offer(self, room_id: str, timeout: float) -> str: ...
    async def publish_answer(self, room_id: str, sdp: str) -> None: ...
    async def wait_answer(self, room_id: str, timeout: float) -> str: ...
    async def close(self) -> None: ...


@runtime_checkable
class ITokenCodec(Protocol):
    def encode_short(self, room_id: str, hmac_short: str) -> str: ...
    def decode_short(self, token: str) -> tuple[str, str]: ...
    def encode_manual(self, sdp: str) -> str: ...
    def decode_manual(self, token: str) -> str: ...
    def is_short(self, token: str) -> bool: ...


@runtime_checkable
class ISessionEvents(Protocol):
    def on_status(self, status: str) -> None: ...
    def on_peer_joined(self, peer: Peer) -> None: ...
    def on_peer_left(self, peer_id: str) -> None: ...
    def on_error(self, error: str) -> None: ...
    def on_disconnected(self) -> None:
        """Called after Disconnect completes; UI should clear tokens etc."""
        ...
